# Custom prompt
export PROMPT="%F{green}%n%f %F{white}%~%f %(!.#.$) "

# User specific aliases and functions
if [[ -d ~/.zshrc.d ]]; then
    for rc in ~/.zshrc.d/*; do
        if [[ -f "${rc}" ]]; then
            source "${rc}"
        fi
    done
fi
unset rc

# Add binaries to PATH
if [[ -f "${HOME}/.local/bin/env" ]]; then
    source "${HOME}/.local/bin/env"
fi
